### ISSUE TITLE
"Sync stock from Square" on the edit product screen is not working when Square is the SOR.

### ISSUE THREAD

**Issue by iamdharmesh** [woocommerce/woocommerce-square#104]
### Describe the bug
While conducting quick testing on #103, I encountered an issue: "Sync stock from Square" on the edit product screen is not functioning when Square is the SOR. It appears to work fine when WooCommerce is the SOR.

### To reproduce
1. Set up the Square plugin and enable sync with inventory sync enabled.
1. Set "Square" as the SOR.
1. Navigate to edit a Square-synced product.
1. Go to the "Inventory" tab of product data and click the "Sync stock from Square" link.
1. Notice that nothing happens.
1. Change the SOR to "WooCommerce."
1. Click the "Sync stock from Square" link on the edit product screen and observe that it appears to work fine.

**Screenshots**
![Screenshot 2024-04-16 at 6 25 45 PM](https://github.com/woocommerce/woocommerce-square/assets/10613171/9de5f5f5-0b6f-473d-8a68-6b4337907b77)

### Expected behavior
Click "Sync stock from Square" on the edit product screen should sync the inventory with Square.

**Environment (please complete the following information):**
 - WordPress Version: 6.5
 - WooCommerce Version: 8.7.0
 - WooCommerce Square Plugin Version: 4.6.1
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by jeffpaul** [comment]
@qasumitbagthariya is there updated coverage on Critical Flows/Test Cases for this?

**Comment by qasumitbagthariya** [comment]
> @qasumitbagthariya is there updated coverage on Critical Flows/Test Cases for this?

Yes, I've updated the critical flow and also discussed it with @iamdharmesh for e2e test.
 
[ Case - 1  Sync Inventory stock from Square - (SOR Square)
](https://github.com/woocommerce/woocommerce-square/wiki/Testing-instructions-for-critical-flows-WooCommerce-Square#sync-inventory-stock-from-square---sor-square)
[ Case - 2 Sync Inventory stock from Square - (SOR WooCommerce)
](https://github.com/woocommerce/woocommerce-square/wiki/Testing-instructions-for-critical-flows-WooCommerce-Square#sync-inventory-stock-from-square---sor-woocommerce)
[ Case - 3 Sync Stock management unchecked
](https://github.com/woocommerce/woocommerce-square/wiki/Testing-instructions-for-critical-flows-WooCommerce-Square#sync-stock-management-unchecked) 
 Thanks

**Comment by jeffpaul** [comment]
@iamdharmesh ideally we can get e2e tests to cover these updated flows ^^^ within the linked PR, so please look into that, thanks!

**Comment by iamdharmesh** [comment]
@jeffpaul @qasumitbagthariya E2E tests are added for this in PR.
