### ISSUE TITLE
[HC] - Weight not syncing to Square (lb instead of lbs)

### ISSUE THREAD

**Issue by OmarFPG** [woocommerce/woocommerce-square#111]
### Describe the bug
Similar to [this issue with GLA](https://github.com/woocommerce/google-listings-and-ads/issues/2388), it seems the weight is not syncing to Square because it is "lbs" in WooCommerce and "lb" in Square.

Could this be the case, or something else entirely? 

### References:
8167941-zen
7737122-zen
7241611-zen
5962915-zen

**Comment by anastas10s-afk** [comment]
From what I understand, there's no weight configuration for Square items.

For reference:
- [The extension's documentation](https://woocommerce.com/document/woocommerce-square/sync-settings/)
- 5962915-zen

**Comment by OmarFPG** [comment]
That makes sense, thanks @anastas10s-afk! I'm marking this one as closed, then.

**Comment by OmarFPG** [comment]
Update from the user, in case anyone else needs this:

> You can input weights into Woocommerce and Square Integration will not override this field. The only thing you can't do at this moment is have Square import those weights, they need to be manually inputted. 

> When a customer orders, the payment is taken at the transaction and is added into Square. It is set up for deposit into the bank account the next day. This wasn't clear to me but I reached out to Square to explain this process.
