### ISSUE TITLE
Reports of "class 'WooCommerce\Square\Gateway\Blocks_Handler' not found" fatal errors

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-square#135]
### Describe the bug

We've received internal reports of some sites we manage getting the following fatal error:

```
PHP Fatal error:  Uncaught Error: Class "WooCommerce\Square\Gateway\Blocks_Handler" not found
in .../plugins/woocommerce-square/woocommerce-square.php:430
```

After looking into this, I found that we're init'ing our blocks handler code and our autoloader behind two different conditions, which results in cases where `register_payment_method_block_integrations()` is trying to call `new WooCommerce\Square\Gateway\Blocks_Handler()` without our autoloader existing.

For instance:

- Registering our blocks handler requires `is_environment_compatible()` to pass which checks for PHP 7.4+
- Init'ing our autoloader requires `is_environment_compatible()` + `plugins_compatible()` which also checks that WP version is 6.3+ and WC version is 8.7+.

What this difference means is if a store has WooCommerce 8.6 installed (an unsupported version), the autoloader won't be init'ed, however, the block handler code will still try to register our block integration classes resulting in the fatal error.

### To reproduce

1. Install and activate WooCommerce 8.6 and the latest WooCommerce Square
1. Load any WP Admin page
1. Note the fatal error: 
![image](https://github.com/woocommerce/woocommerce-square/assets/2275145/a13bc817-d9b2-4c30-b6f4-e0bf25466edf)

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - WooCommerce Square Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by shameemreza** [comment]
Another report here: 8261040-zen
Thread: https://wordpress.org/support/topic/critical-error-when-activating-plugin-4/
