### ISSUE TITLE
The "Buy Gift Card" button doesn't match the style of the "Add to Cart" button on the TT4.

### ISSUE THREAD

**Issue by iamdharmesh** [woocommerce/woocommerce-square#140]
### Describe the bug
The "Buy Gift Card" button of the Square Gift card product doesn't match the style of the "Add to Cart" button on the TT4(Twenty Twenty-Four) Theme. It matches the style on Storefront but not match on the TT4.

### To reproduce
1. Activate  TT4(Twenty Twenty-Four) Theme
1. Create a Gift Card Product
1. Visit the Shop page and notice that the "Buy Gift Card" button doesn't match the style of the "Add to Cart" button

**Screenshots**
![Screenshot 2024-05-31 at 1 04 51 PM](https://github.com/woocommerce/woocommerce-square/assets/10613171/d7689b28-2525-4843-8406-38c7992c0cff)

### Expected behavior
The "Buy Gift Card" button should match the style of the "Add to cart" button on the TT4(Twenty Twenty-Four) Theme. 

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - WooCommerce Square Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by faisal-alvi** [comment]
Hey @Sidsector9,

I noticed that the issue disappears when we stop using the `woocommerce_loop_add_to_cart_link` filter.

https://github.com/woocommerce/woocommerce-square/blob/d12bbbf2f5cf10d39e8e9b967377e37bdd5ad289/includes/Handlers/Products.php#L136

It looks like this was added in https://github.com/woocommerce/woocommerce-square-private/pull/1031. I tried removing the filter, and the "Buy Gift Card" button text still shows correctly on the shop page. Is it safe to remove this filter entirely?
