### ISSUE TITLE
[Post-NUX] Move Digital Wallets to Payments Level

### ISSUE THREAD

**Issue by faisal-alvi** [woocommerce/woocommerce-square#148]
### Describe the bug

Move the Digital Wallets outside the Square Credit Card Payment Gateway and make a standalone payment gateway.

### To reproduce

n/a

### Expected behavior

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - WooCommerce Square Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by slash1andy** [comment]
Is this the same as #102 ? @vikrampm1 @jeffpaul @faisal-alvi

**Comment by faisal-alvi** [comment]
You're right @slash1andy. Thanks for pointing this out. Closing as a duplicate.
