### ISSUE TITLE
[HC] Categories reverting to the default category on sync when Square is set as SOR

### ISSUE THREAD

**Issue by OmarFPG** [woocommerce/woocommerce-square#156]
### Describe the bug
When using Square as the Sync option, the products in WooCommerce get assigned the default category (typically Uncategorized, but if you set any other as the default, it'll pick that one), not the category the product has in Square.

Reportedly an issue in 4.6.3.

Edit 1: some merchants have confirmed rolling back to 4.6.2 resolves the issue so this is the current workaround.
Edit 2: the bug is still present on 4.7.

### Additional details
8368651-zen
8362121-zen

**Comment by dsmithweb-a8c** [comment]
8361657-zen

**Comment by dsmithweb-a8c** [comment]
8370689-zen

**Comment by OmarFPG** [comment]
8394034-zen

**Comment by carolframen** [comment]
8397799-zen

**Comment by rajwpdev117** [comment]
8398366-zen

**Comment by haleyndixon** [comment]
8399155-zd-a8c

**Comment by MariaChek** [comment]
8391261-zen

**Comment by carolframen** [comment]
8406693-zen

**Comment by rajwpdev117** [comment]
8392399-zen

**Comment by rajwpdev117** [comment]
8410849-zen

**Comment by smartsite4u** [comment]
Updating this to saw that I am having the exact same issue, it has affected our client's site as everything was linked via Categories and suddenly everything was Uncategorised.

We have rolled back to 4.6.2 and it seems to be working now.

Hoping a fix is implemented ASAP.

**Comment by ericfri** [comment]
8443877-zen

**Comment by ericfri** [comment]
8438263-zen

**Comment by cardehngeh** [comment]
8470848-zen

**Comment by ericfri** [comment]
8466204-zen

**Comment by dsmithweb-a8c** [comment]
Just came across what I strongly suspect is another instance. this bug is definitely breaking users' sites -- would it be possible to get the fix confirmed so we could send a pre-release with the fix to affected users?

**Comment by ericfri** [comment]
8304245-zen

**Comment by ericfri** [comment]
8483660-zen

**Comment by ericfri** [comment]
8489338-zen

**Comment by ericfri** [comment]
8454167-zen

**Comment by ericfri** [comment]
8482378-zen

**Comment by dsmithweb-a8c** [comment]
8516892-zen

**Comment by ericfri** [comment]
8501072-zen

**Comment by ericfri** [comment]
8474599-zen

**Comment by carolframen** [comment]
8533033-zen

**Comment by sunile2m** [comment]
By reading the thread history and from the number of tickets on the wordpress.org forum, I can see the issue is still open for the last 2 months. Can you guys pls fix it asap? it is breaking the client's website completely.

@iamdharmesh bhai, pls do something :)
