### ISSUE TITLE
Modernize developer experience // Fix linter issue for includes/Plugin.php

### ISSUE THREAD

**Issue by shendy-a8c** [woocommerce/woocommerce-square#17]
### Describe the bug

As a follow up of https://github.com/woocommerce/woocommerce-square-private/pull/1006 to make that PR 'small', there are some unresolved linter issues for `includes/Plugin.php`.

### To reproduce

```
composer install
./vendor/bin/phpcs includes/Plugin.php
```

### Expected behavior

No linter issue for `includes/Plugin.php`.

**Comment by Sidsector9** [comment]
@vikrampm1 this can be closed:

<img width="1002" alt="Screenshot 2024-07-15 at 4 17 32 PM" src="https://github.com/user-attachments/assets/cc385d6f-7914-40f7-b963-5c0f6b89c59e">

Ref: trunk(74e40c0b866bcf525f6d0a360fb323ef86602e90)

**Comment by Sidsector9** [comment]
Closing as already fixed.
