### ISSUE TITLE
Gift Card image forced upon a site

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-square#30]
### Describe the bug

I've some feedback on the default Gift Card placeholder image. On a site, even if not using gift cards, you get the [gift card placeholder](https://github.com/woocommerce/woocommerce-square/blob/57f5ca735cfaed40dfb2ecee57659a807fd4cbaa/includes/Gateway/Gift_Card.php#L104C1-L104C1) image forced into your media library.

This has caused some merchants to worry there was a security issue on their site with a random image appearing. Especially since it's not clear from the image where it came from, and you can't delete it. That seems very suspicious from that perspective.

### To reproduce

1. Activate Square
2. Look in media library
3. See placeholder image

**Screenshots**

<img width="1417" alt="Screenshot 2023-09-12 at 12 17 31 PM" src="https://github.com/woocommerce/woocommerce-square/assets/867748/8bb6fe6f-20d9-4897-b8f8-68d7605f6fee">

### Expected behavior

I think there are two areas and things we could look to improve. First, If adding an image for a merchant, is there any way to make that clearer? Do we need explicit permission, or can we add more metadata to the image to make it clear where this came from?

<img width="494" alt="Screenshot 2023-09-12 at 12 29 48 PM" src="https://github.com/woocommerce/woocommerce-square/assets/867748/c7b9104b-1282-4bd0-a2e1-3f60c3bc6c4e">

Also, why can't the image being deleted. I mean, it can be deleted, but the linked to function above adds it right back. That seems to take away some control from the merchant, and can seem sketchy if you already don't know where this image is coming from.

**Comment by OmarFPG** [comment]
7875446-zen

**Comment by vikrampm1** [comment]
@Sidsector9 I am moving this back to To Do. Please review/pick it back up when you resume looking into this.

**Comment by OmarFPG** [comment]
8277030-zen, some images from Sucuri alerts were added to this ticket.
