### ISSUE TITLE
Add Product Editor Compatibility

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-square#40]
[Declare compatibility](https://github.com/woocommerce/woocommerce/blob/trunk/docs/product-editor-development/README.md#declaring-compatibility-with-the-product-editor) for this extension with the WooCommerce Product Editor by integrating with the Groups, Sections, and Fields as described in the [Product Editor Development Handbook](https://github.com/woocommerce/woocommerce/blob/trunk/docs/product-editor-development/README.md#product-editor-development-handbook).

- [ ] If the extension doesn’t interact with the product editor, then declare compatibility without any sort of testing.
- [ ] If the extension interacts with the product editor and doesn't have existing e2e tests that interact with the editor, then add those e2e tests.
- [ ] If the extension interacts with the product editor and has e2e tests that interact with the editor, then ensure those tests run and pass successfully.
- [ ] Add compatibility fixes where necessary.

**Comment by Sidsector9** [comment]
@diegocurbelo I've partially added the necessary product metabox fields to the block product editor.
I need some pointers on few blockers I'm facing:

<img width="862" alt="Screenshot 2024-01-23 at 8 23 20 PM" src="https://github.com/woocommerce/woocommerce-square/assets/17757960/0b5208b1-4843-4db5-8058-086be02b6d20">

<img width="896" alt="Screenshot 2024-01-23 at 8 23 54 PM" src="https://github.com/woocommerce/woocommerce-square/assets/17757960/aeac4b54-dabe-4acc-8bc1-1f67d90bdc54">


I couldn't find in the Woo docs. Is there a way I can extend the fields to add the texts shown in the images above? Even better would be to make them conditional?

**Comment by jeffpaul** [comment]
Noting that this work is blocked by https://github.com/woocommerce/woocommerce/issues/45143
