### ISSUE TITLE
VERSION MISMATCH error during manual sync of large square store

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-square#44]
### Describe the bug

We have a large merchant with 9,000 products that cannot run the manual sync process because it continuously fails with a VERSION_MISMATCH error (see logs below). It's worth noting that the regular automated sync is working fine and is running every 15 minutes, just the full manual sync cannot complete.

We saw this version mismatch error many years ago during the `upserting_categories` step (https://github.com/woocommerce/woocommerce-square-private/issues/277), which we later fixed in https://github.com/woocommerce/woocommerce-square-private/pull/374, but this error is being thrown during `update_matched_products` which I don't think we've seen before.

I couldn't replicate the issue myself on a Square store with 150 products and I can't find much information on the VERSION_MISMATCH error but my understanding is that between the time that we fetched the product from Square and when we tried to update it, the product has been updated on Square's end and so Square throws this version mismatch error to avoid overriding the product with out-of-date data.

**Customer problem:**

I think it's also worth pointing out that the main pain point for this merchant is that they're running a manual sync to fetch all of their inventory updates from Square, but the manual sync keeps failing earlier in the process and exiting before it gets to the `pull_inventory` step.

Given this, on top of fixing a potential issue that might be causing the VERSION MISMATCH error, I wonder if we could also improve the manual sync process for merchants by continuing the rest of the manual sync even when there's an error 🤔 ?

---
```
01-05-2024 @ 16:38:32 - Response
 Response
code: 400
message:
headers: Array
(
    [0] => HTTP/2 400
    [date] => Fri, 05 Jan 2024 05:38:32 GMT
    [content-type] => application/json
    [content-length] => 159
    [cf-ray] => 84095fe5fb75aae4-SYD
    [cf-cache-status] => DYNAMIC
    [content-encoding] => gzip
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [vary] => Origin, Accept-Encoding
    [square-version] => 2023-07-20
    [x-content-type-options] => nosniff
    [x-download-options] => noopen
    [x-envoy-decorator-operation] => /v2/catalog/**
    [x-frame-options] => SAMEORIGIN
    [x-permitted-cross-domain-policies] => none
    [x-speleo-traceid] => CDN-a3beb1dd-016f-4fd1-a102-56c175c91a5f
    [x-sq-dc] => aws
    [x-sq-region] => us-west-2
    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm={readacted}; path=/; expires=Fri, 05-Jan-24 06:08:32 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [server] => cloudflare
)
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => VERSION_MISMATCH
            [detail:Square\Models\Error:private] => Object version does not match latest database version.
            [field:Square\Models\Error:private] => version
        )

)

01-05-2024 @ 16:38:32 - Failed step cycle: update_matched_products (310.20s) - [VERSION_MISMATCH] Object version does not match latest database version.
01-05-2024 @ 16:38:32 - [VERSION_MISMATCH] Object version does not match latest database version.
```

### To reproduce

I couldn't replicate locally, however, this store has WooCommerce set as their System of Record and their process is to update stock in Square, then run a manual sync to pull in those inventory adjustments.

**Screenshots**

### Expected behavior

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - WooCommerce Square Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by Sidsector9** [comment]
Okay, so with some workaround I was able to reproduce this issue. Just for future reference, these are the steps I followed:

- Delete all products from Woo and Square dashboard.
- Create just 1 product in Woo and sync it with Square.

After this line:

https://github.com/woocommerce/woocommerce-square/blob/57f5ca735cfaed40dfb2ecee57659a807fd4cbaa/includes/Sync/Manual_Synchronization.php#L474

Add the following code:

```php
error_log( __FUNCTION__ . '..sleeping for 20 seconds..' );
sleep( 20 ); // We put the script to sleep for 20 seconds immediately after catalog objects are retrieved.
error_log( __FUNCTION__ . '..resumed..' );
```



- Once you see the message **sleeping for 20 seconds** in the log file, edit any parameter of the product in Square and save. This will update the version number of the catalog item in Square. **Save the changes before our script resumes.**
- Now wait for the sync to finish.
- Observe the sync fail.

---

What I have noticed is that performing manual syncing again succeeds and restores the catalog item in Square.

@mattallan do we know whether the customer is updating catalog items in Square while the store is syncing?

> Given this, on top of fixing a potential issue that might be causing the VERSION MISMATCH error, I wonder if we could also improve the manual sync process for merchants by continuing the rest of the manual sync even when there's an error 🤔 ?

This will require some in-depth analysis. A lot of sync steps depend on the data set by the previous step.
I'll see what we can do to improve the process.

**Comment by mriyazuddin** [comment]
User has replied back saying they're not sure. Their website is set to sync every 15 mins and when they're working in Square they're not sure if the sync is taking place so hard to tell if they were editing the products at the time when sync was going on.

**Comment by Sidsector9** [comment]
I've investigated this issue further to find ways to continue the sync on error and this is the report:

The reported error occurs during the batch upsert stage which immediately follows batch retrieve. In code, this happens when an item is updated in Square between these 2 stages (where the version changes after save).

When the batch upsert fails, the response _does not_ contain any information about which product has specifically caused the failure.

Having this information would have been beneficial to exclude the failed product from any further sync steps, and would help in continuing the sync for other products. With the level of information we have from the failed steps, we cannot continue the sync job.

---

@mriyazuddin I have a follow up question regarding this comment:

> Their website is set to sync every 15 mins and when they're working in Square they're not sure if the sync is taking place

- As per the issue description, the **Sync setting** (formerly System of Record) is set to WooCommerce on this store – which ideally means the products and inventory are both managed in WooCommerce. Do you have any details on what the store owner means by "when they're working in Square"? Are they updating the products in Square while the Sync setting is set to WooCommerce?
- Can we ask the store owner to perform a Manual Sync again and make sure that no changes are done in Square? And if needed, changes must to be done through WooCommerce?

**Comment by mriyazuddin** [comment]
I have asked user to confirm if they edit products in Square. I have asked them to edit products in Woo, do a manual sync and check. Also, suggested changing the sync settings to Square if they have to edit products in Square, try a manual sync and check.

**Comment by vikrampm1** [comment]
@mriyazuddin just checking here to see if there is any feedback from the merchant on the above steps or if there is any further help needed from us?

**Comment by imodouglas** [comment]
Hi @vikrampm1, we heard back from the merchant and this was their reply:

> I am using Woo Commerce as my basic, where I load new stock and remove stock when sold out. 
> I use Square in the shop for retail sales and the inventory gets adjusted by Square in that process!

Is this helpful in any way?

**Comment by jeffpaul** [comment]
@mattallan @imodouglas it would be very helpful to have a system health info export with the WP, WC, Square versions (as well as the other active plugins & versions) plus where feasible a screencast/recording of the issue.  No one from Woo or 10up has been able to replicate this issue, so until we can there's not too much we can do to help here (noting that @Sidsector9 already dug through the code to see where this error could be thrown and is not seeing anything obviously of concern).

**Comment by vikrampm1** [comment]
Closing this issue as not re-producible. Please re-open if there are any reproduction steps or additional info as requested above from the merchant.
