### ISSUE TITLE
Replace the middleware URL from `connect.woocommerce.com` to `api.woocommerce.com/integrations`

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/woocommerce-square#80]
The `connect.woocommerce.com` server is due to be retired. The `api.woocommerce.com`  server now provides the connect service. The base URL will now be `api.woocommerce.com/integrations`. All other endpoints should now be accessible from the base URL.

## Endpoints

- [ ] `/login/square`
- [ ] `/auth/square`
- [ ] `/renew/square`
- [ ] `/revoke/square`
- [ ] `/login/squaresandbox`
- [ ] `/auth/squaresandbox`
- [ ] `/renew/squaresandbox`
- [ ] `/revoke/squaresandbox`

**Comment by faisal-alvi** [comment]
I've submitted PR #83, but there's a connection issue that appears to require attention from the WooCommerce side.

The plugin consists of four URLs that are replaced:

* Connection URL (Production)
* Refresh URL (Production)
* Connection URL (Sandbox)
* Refresh URL (Sandbox)

### Connection URL (not working ❌)

Upon testing the connection URL, it appears to be functional; however, it returns a faulty redirect URL, preventing a successful connection.

For instance, with the previous middleware URL `connect.woocommerce.com`, we received:

```
http://wpne3.local/wp-admin/?action=wc_square_connected&_wpnonce=6561f3bd49&square_access_token=hidingtheactualtokenforprivacypurposes&expires_at=2024-04-18T11%3A05%3A35Z&merchant_id=ABCD&subscription_id=&plan_id=&square_refresh_token=hidingtheactualtokenforprivacypurposes
```
![image](https://github.com/woocommerce/woocommerce-square/assets/25176325/4574ec08-329b-4111-9091-e0efe2323503)

But with the updated middleware URL `api.woocommerce.com/integrations`, we're getting:

```
https://connect.woocommerce.com/auth/http%3A%2F%2Fwpne3.local%2Fwp-admin%2F%3Faction%3Dwc_square_connected%26amp%3B_wpnonce%3D6561f3bd49?square_access_token=hidingtheactualtokenforprivacypurposes&expires_at=2024-04-18T11%3A08%3A31Z&merchant_id=ABCD&subscription_id=&plan_id=&square_refresh_token=hidingtheactualtokenforprivacypurposes
```
![image](https://github.com/woocommerce/woocommerce-square/assets/25176325/3b4c9ff1-7541-45da-84a3-2e086c67fd01)

This URL format is incorrect and leads to the 404 page.

<img width="637" alt="Screenshot 2024-03-19 at 4 28 53 PM" src="https://github.com/woocommerce/woocommerce-square/assets/25176325/3dd1e023-3fdc-4293-89fc-c58ba0f96345">

It seems like it should be updated from the Woo end.

### Refresh URL (working ✅)

The refresh URL has been tested and functions correctly, as expected.

<img width="683" alt="image" src="https://github.com/woocommerce/woocommerce-square/assets/25176325/d1a773ff-f710-41eb-ab63-7870527a86d9">

**Comment by ibndawood** [comment]
Thank you, @faisal-alvi, for reporting this. I'll go through this and shall get back to you as soon as possible.

**Comment by ibndawood** [comment]
Hello again, @faisal-alvi. Thank you for your patience. We have an issue with setting the redirect URI. Currently, we can only set one redirect URI, and it is in production, so we do not want to change it now. 

To enable testing, we've setup a separate application in our staging. Can you please try using `api-staging.woocommerce.com` instead of `api.woocommerce.com`? Once we've tested the endpoints within the plugin, we'll change the redirect URI in production to `api.woocommerce.com`. Please let me know if the PR tests as expected.

**Comment by faisal-alvi** [comment]
@ibndawood thanks for the update. I re-tested and the application on the staging works as expected.

The middleware redirect URL is working as earlier and correctly redirecting with a successful connection.
