### ISSUE TITLE
NUX Updates to Merchant Onboarding 

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-square#89]
To review and improve the merchant onboarding experiences and make WooCommerce + Square integration and sync settings more intuitive. To improve the ability for the Square extension to be quickly set up when used only for payment processing and  minimise the number of steps and checkboxes that the merchants have to perform the WooCommerce + Square integration and sync, making it seamless and more intuitive. This enhancement includes the following tasks:

- [ ] Map the UX flows to set up Square more quickly when used only for payment processing
- [ ] Map the UX flows to minimize the number of steps and checkboxes that the merchants have to perform the WooCommerce + Square integration and sync
- [ ] Map the additional UX flows, as necessary, for any additional merchant onboarding recommendations
- [ ] Add e2e tests where necessary

**Comment by Sidsector9** [comment]
The following list describes the subtasks for NUX:

- [x] Set up the tooling & folder structure to organize components, hooks and utils.
- [x] Register an admin settings page to mount the App wrapper.
- [ ] Implement smallest reusable components referring to [this figma](https://www.figma.com/file/fMysPY0YQRXWWLCU0RL2En/WooCommerce-Square-Plugin-Onboarding-Wizard?type=design&node-id=1985-4551&mode=design&t=XvCyzow3fEmSLOpE-0). This will be used to build larger modules.

For example, the ones in red below are the smallest components reused everywhere :
![Group 37338](https://github.com/woocommerce/woocommerce-square/assets/17757960/fb1d58a4-ed29-4b9b-b165-573a88a78190)

Some of the smallest components are readily available in `wordpress/components` and `woocommerce/components`.

[Atomic design methodology](https://atomicdesign.bradfrost.com/chapter-2/#atoms) is a good read to build from bottom-up.

- [ ] Once we have all the smallest components, implement modules.

The following can be considered as modules:

![Group 37338](https://github.com/woocommerce/woocommerce-square/assets/17757960/9c59edd6-ce95-43f9-93c7-784e6da8272d)
---
![Group 37349](https://github.com/woocommerce/woocommerce-square/assets/17757960/82ff6369-31df-4973-86aa-ff5419927298)
---
![Group 37366](https://github.com/woocommerce/woocommerce-square/assets/17757960/8e7733a5-2c8e-4462-9293-19ea8ba3e2ab)

(Ensure the modules has the necessary props to set and update the children components.

- [ ] Implement logic using hooks to get/set admin settings.

---

Sub task branches:

- nux-react (parent branch)
    - tooling
    - wizard_page
    - components
    - hooks

Once all branches are merged to `nux-react`, we can integrate the module to build the steps.

cc: @faisal-alvi
