### ISSUE TITLE
Square Access Token Spam Notifications

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-square#92]
While testing the Square plugin, the user got spammed with notifications about their Square access token and after 30+ they were marked as spam.

![Square_access_token](https://github.com/woocommerce/woocommerce-square/assets/93216400/a60f7199-44f4-43d3-b4a2-009ddcb7a44f)

There should really only be one or two of these notifications.

**Comment by iamdharmesh** [comment]
@jeffpaul @vikrampm1 This issue seems related to #93 and it is already fixed in #94. We are good to proceed with close this.

Thanks

cc: @Sidsector9
